### PR TITLE
Reports model, controller and backend fixes done

### LINKED ISSUE #18: Reports model, controller and backend fixes
# REQUIREMENTS
-Attendance
-Average check in/out times 
-Absence report by month

### PR DESCRIPTION
**Pull request by javs1**
reports.scss
 - deleted calendar class
 - added max height for the table
aplication_controller.rb
 - added a notice when redirectin to admin login
employee_crud_controller.rb
 - added before action that requires login
reports_controller.rb
 - added before action that requires login
 - method index get the absences
 - method index get the atendances
 - method index get checking hour average
 - method index get checkout hour average
reports_helper.rb
 - avg_time method that returns the average hour
 - absences methot that returns an array of the employee that have
   absences
aplication.js
 - deleted fullcalendar
reports.js deleted
employee_crud index.html.erb
 - modified navbar to redirect to reports_path
reports index.html.erb
 - deleted full calendar
 - added a table for atendance
 - absence modal shows the employees and their private number

Co-authored-by: javs1 <javierverduzco13@gmail.com>
Co-authored-by: Joshsam31 <samano82324@gmail.com>

# Description
What did you implemented/Why did you implemented this:
 - Explain the changes you’ve made.
 - It doesn’t need to be fancy and you don’t have to get to technical, yet.
 - Just explicit what you have implemented at a high level.
 - Let the reviewer know the overall effect of the PR.
 - Reference a ticket in your issue tracker. Explain what the change is and then and only then reference the ticket.
 - The “why” is a chance to explain both the engineering goal, but also a some business objective that is satisfied or moved along.

 Examples:
 - What?: I've added support for authentication to implement Key Result 2 of OKR1. It includes
model, table, controller and test. For more background, see ticket #JIRA-123.
 - Why?: These changes complete the user login and account creation experience. See #JIRA-123 for more information.

 # Testing
 Help me how can I test or look at the changes

 Example:
  - I've added coverage for testing all new methods. I used Faker for a few random user emails and names.

  ## Screenshots
If applicable, include screenshots of the results or screenshots that help to see changes

### CODE REVIEW

File: app/controllers/employee_crud_controller.rb [hunk 1]
```diff
@@ -1,4 +1,5 @@
   class EmployeeCrudController < ApplicationController
+    before_action :require_login
```
Comment (ccarruitero) [inline app/controllers/employee_crud_controller.rb:2]: You could set this before action in application_controller .. that way will apply to all your controllers

File: app/helpers/reports_helper.rb [hunk 2]
```diff
@@ -1,2 +1,31 @@
 module ReportsHelper
+
+  def avg_time(checks)
+    if checks.size > 0 
+        avg = checks.size 
+        avg_minutes = checks.map do |p|
+        hour, minute = p.hour.strftime('%H:%M').to_s.split(':')
+        total_minutes = hour.to_i * 60 + minute.to_i
+        end.inject(:+)/avg
+        "#{avg_minutes/60}:#{avg_minutes%60}"
```
Comment (ccarruitero) [inline app/helpers/reports_helper.rb]: take care about indentation

File: app/controllers/employee_crud_controller.rb (hunk 1 above)
Comment (javs1) [reply app/controllers/employee_crud_controller.rb:2]: There are 2 pages that doesnt need the login, thats why the require_login is not in application_controller
