### PR TITLE
Branches crud frontend, backend and other fixes

### LINKED ISSUE #23: Branches crud frontend, backend and other fixes
# REQUIREMENTS
A CRUD to manage the branches 
Store: name, address

### PR DESCRIPTION
**Pull request by javs1**
removed vue
removed jquery from environment.js in webpack config
routes.rb
 - added branches get for the branches_crud view
 - added post create_branch for the branches#create controller method to
   add a branch
 - added post edit_branch to edit branches with the method edit in
   branch_crud controller
 - added post delete_branch route to delete branch with the metod delete
   in branch_crud controller
employee_crud index.html.erb
 - added a href for the branches_path in the navbar
application.js
 - deleted import bootstrap line because it caused an error
 - deleted import aplication.scss because it caused an error
branch_crud_controller.rb
 - index method that return all branches
 - create method that insert a new branch in database
 - edit method that update a branch in the database
 - delete methot that delete a branch in database

Co-authored-by: javs1 <javierverduzco13@gmail.com>
Co-authored-by: Joshsam31 <samano82324@gmail.com>

# Description
What did you implemented/Why did you implemented this:
 - Explain the changes you’ve made.
 - It doesn’t need to be fancy and you don’t have to get to technical, yet.
 - Just explicit what you have implemented at a high level.
 - Let the reviewer know the overall effect of the PR.
 - Reference a ticket in your issue tracker. Explain what the change is and then and only then reference the ticket.
 - The “why” is a chance to explain both the engineering goal, but also a some business objective that is satisfied or moved along.

 Examples:
 - What?: I've added support for authentication to implement Key Result 2 of OKR1. It includes
model, table, controller and test. For more background, see ticket #JIRA-123.
 - Why?: These changes complete the user login and account creation experience. See #JIRA-123 for more information.

 # Testing
 Help me how can I test or look at the changes

 Example:
  - I've added coverage for testing all new methods. I used Faker for a few random user emails and names.

  ## Screenshots
If applicable, include screenshots of the results or screenshots that help to see changes

### CODE REVIEW

File: app/controllers/branch_crud_controller.rb [hunk 1]
```diff
@@ -0,0 +1,40 @@
+class BranchCrudController < ApplicationController
```
Comment (EduardoGHdez) [inline app/controllers/branch_crud_controller.rb]: It's not necessary to include the word `Crud`

Usually, controllers are in plural as well

I'd suggest something like `BranchesController`, but it's not necessary, it was just a code smell to me 😄

File: app/views/branch_crud/index.html.erb [hunk 2]
```diff
@@ -0,0 +1,169 @@
+<!DOCTYPE html>
+  <html>
+  <head>
+  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
+  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
+  </head>
+  <body>
```
Comment (EduardoGHdez) [inline app/views/branch_crud/index.html.erb]: This is not needed at all, rails views only load the content while the application.html.erb file does content the "layout", loads the styles and the js/scripts 😄 

Consider taking a look to this resource https://guides.rubyonrails.org/layouts_and_rendering.html

File: app/views/branch_crud/index.html.erb [hunk 3]
```diff
@@ -0,0 +1,169 @@
...
+          </li>
+          <li class="nav-item">
+            <a class="nav-link" href="#">Reports</a>
+          </li>
+          <li class="nav-item active">
+            <a class="nav-link" href="#">Branches</a>
+          </li>
+        </ul>
+      </div>
+    </nav>
```
Comment (EduardoGHdez) [inline app/views/branch_crud/index.html.erb]: This could be moved to a shared-view, or event (it depends) to the application-layout

File: yarn.lock [hunk 4]
```diff
@@ -6836,11 +6836,6 @@ vue-template-es2015-compiler@^1.9.0:
   resolved "https://registry.yarnpkg.com/vue-template-es2015-compiler/-/vue-template-es2015-compiler-1.9.1.tgz#1ee3bc9a16ecbf5118be334bb15f9c46f82f5825"
   integrity sha512-4gDntzrifFnCEvyoO8PqyJDmguXgVPxKiIxrBKjIowvL9l+N66196+72XVYR8BBf1Uv1Fgt3bGevJ+sEmxfZzw==
 
-vue@^2.6.14:
-  version "2.6.14"
-  resolved "https://registry.yarnpkg.com/vue/-/vue-2.6.14.tgz#e51aa5250250d569a3fbad3a8a5a687d6036e235"
-  integrity sha512-x2284lgYvjOMj3Za7kqzRcUSxBboHqtgRE2zlos1qWaOye5yUmHn42LB1250NJBLRwEcdrB0JRwyPTEPhfQjiQ==
-
```
Comment (EduardoGHdez) [inline yarn.lock:6843]: 🔪 nuking vue huh!? XD

Comment (BrandonVG) [reply yarn.lock:6843]: Yes, because at the start of the proyect we added a clock that nedeed vue but we changed it for other that does not require it and we forget to deled vue until now haha

File: app/views/branch_crud/index.html.erb (hunk 3 above)
Comment (javs1) [reply app/views/branch_crud/index.html.erb]: The navbar is not used in the employee page and login, we can't put it in application-layout

File: app/controllers/branch_crud_controller.rb (hunk 1 above)
Comment (BrandonVG) [reply app/controllers/branch_crud_controller.rb]: We changed the name

File: app/controllers/branches_controller.rb [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+    else
+      render :new
+    end
+  end
+
+  def edit
+    @branch = Branch.find(params[:id])
+    if @branch.update(:store=>params[:store],:name=>params[:name],:address=>params[:address])
+      redirect_to branches_path
+    end
```
Comment (YilKanda) [inline app/controllers/branches_controller.rb]:
```suggestion
    redirect_to branches_path if @branch.update(store: params[:store], name: params[:name], address: params[:address])
```

File: app/controllers/branches_controller.rb [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+  end
+  
+  def delete
+    @branch = Branch.find(params[:id])
+    if @branch.destroy
+      redirect_to branches_path
+    end
```
Comment (YilKanda) [inline app/controllers/branches_controller.rb]:
```suggestion
    redirect_to branches_path if @branch.destroy
```

File: app/views/branches/index.html.erb [hunk 7]
```diff
@@ -0,0 +1,160 @@
...
+      <div class = "row justify-content-end " >
+        <div class ="col-1" >
+          <form action="/logout" method="post">
+            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
+            <div class="dropdown show">
+              <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
+                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
+                  <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"></path>
+                  <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"></path>
+                </svg>
```
Comment (YilKanda) [inline app/views/branches/index.html.erb]: What do you think about exporting this SVG from an external file?

File: app/views/branches/index.html.erb [hunk 8]
```diff
@@ -0,0 +1,160 @@
...
+    <div class = "container mt-5">
+      <div class = "row justify-content-center">
+        <div class ="col-10" >
+            <div class="input-group justify-content-center">
+              </div>
+              <button type="button" class="btn btn-success ml-3" data-toggle="modal" data-target="#addBranch">
+                Add branch
+                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square-fill" viewBox="0 0 16 16">
+                  <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"></path>
+                </svg>
```
Comment (YilKanda) [inline app/views/branches/index.html.erb]: What do you think about exporting this SVG from an external file?

File: app/views/branches/index.html.erb [hunk 9]
```diff
@@ -0,0 +1,160 @@
...
+              <% @branches.each do |branch|%>
+                <tr>
+                  <th scope="row"><%= branch.store%></th>
+                  <td><%= branch.name%></td>
+                  <td><%= branch.address%></td>
+                  <td>
+                    <button type="button" id="<%= branch.id %>" data-toggle="modal" data-target="#editBranch<%= branch.id %>" class="btn btn-success">
+                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
+                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"></path>
+                      </svg>
```
Comment (YilKanda) [inline app/views/branches/index.html.erb]: What do you think about exporting this SVG from an external file?

File: app/views/branches/index.html.erb [hunk 10]
```diff
@@ -0,0 +1,160 @@
...
+                  </td>
+                  <td>
+                    <form method="post" action="/delete_branch">
+                      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
+                      <input type="hidden" name ="id" value="<%= branch.id %>" id ="id" class="form-control" placeholder="privateNumber">
+                      <button type="submit" class="btn btn-danger">
+                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-x" viewBox="0 0 16 16">
+                        <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
+                        <path fill-rule="evenodd" d="M12.146 5.146a.5.5 0 0 1 .708 0L14 6.293l1.146-1.147a.5.5 0 0 1 .708.708L14.707 7l1.147 1.146a.5.5 0 0 1-.708.708L14 7.707l-1.146 1.147a.5.5 0 0 1-.708-.708L13.293 7l-1.147-1.146a.5.5 0 0 1 0-.708z"/>
+                      </svg>
```
Comment (YilKanda) [inline app/views/branches/index.html.erb]: What do you think about exporting this SVG from an external file?

File: app/views/branches/index.html.erb [hunk 11]
```diff
@@ -0,0 +1,160 @@
...
+								</div>
+								<div class="input-group form-group">
+									<input type="text" name="name" id="name" class="form-control" placeholder="name">
+								</div>
+                <div class="input-group form-group">
+									<input type="text" name="address" id="address" class="form-control" placeholder="address">
+								</div>
+								<div class="form-group">
+									<input type="submit" value="Add" class="btn btn-success float-right">
+								</div>
```
Comment (YilKanda) [inline app/views/branches/index.html.erb]: Check the indentation in this file

File: app/views/branches/index.html.erb [hunk 12]
```diff
@@ -0,0 +1,160 @@
...
+            </form>
+          </div>
+        </div>
+      </div>
+    </div>
```
Comment (YilKanda) [inline app/views/branches/index.html.erb]: Add a blank line

File: app/assets/stylesheets/employee.scss [hunk 13]
```diff
@@ -164,3 +164,6 @@ input:checked + .slider:before {
   margin-left: 300px;
 }
 
+#notice{
+  text-align: center;
+}
```
Comment (YilKanda) [inline app/assets/stylesheets/employee.scss]: Add a blank line

File: app/views/reports/index.html.erb [hunk 14]
```diff
@@ -214,23 +56,17 @@
...
->>>>>>> 2eb8759 (Added check in/out and absence report desing)
-<<<<<<< HEAD
-=======
-=======
->>>>>>> 28daa45e22760aef1630bdba612cb3f090bbe16f
->>>>>>> 1ec41e58e05d3e8752f609faf3a89e10ee19cd96
-  </body>
-</html>
\ No newline at end of file
+        </div>
```
Comment (YilKanda) [inline app/views/reports/index.html.erb]: Add a blank line
