### PR TITLE
Crud backend and fixes done

### LINKED ISSUE #13: crud-backend and fixes
# REQUIREMENTS
Controller for the crud to 

Generate a table with all employes
Add employees
Edit employees
Disable employees
Generate a table with all employees of a branch
Add to the crud view a modal for edit and add employees

### PR DESCRIPTION
**Pull request by javs1**
Modified routes.rb
 - added post route to logout and destroy session
 - added post route to create and save employee in database+
 - added post route editEmployee to edit employee and save changes
 - added get rout with id to get all employees from a branches in crud
crud view frontend fixes
 - added modal to add new employees
 - added modal to edit employees
 - added new table row for disable button
 - added new table row for status of the employee
 - deleted search bar
 - the table now updates with the employees of the database
 - branches dropdown now updates with al the branches
crud controller
 - modified index method to show all employes and branches
 - method logout to destroy session
 - method new to make a new employee
 - method create to save in database a new employee
 - method edit to edit an employee  and save it
 - method disable to disable or enable an employee
aplication controller changes
 - added a method require_login that in case there no are session does
   redirect to login page
Created branch model
Created employee model

Co-authored-by: Joshsam31 <samano82324@gmail.com>
Co-authored-by: javs1 <javierverduzco13@gmail.com>

# Description
What did you implemented/Why did you implemented this:
 - Explain the changes you’ve made.
 - It doesn’t need to be fancy and you don’t have to get to technical, yet.
 - Just explicit what you have implemented at a high level.
 - Let the reviewer know the overall effect of the PR.
 - Reference a ticket in your issue tracker. Explain what the change is and then and only then reference the ticket.
 - The “why” is a chance to explain both the engineering goal, but also a some business objective that is satisfied or moved along.

 Examples:
 - What?: I've added support for authentication to implement Key Result 2 of OKR1. It includes
model, table, controller and test. For more background, see ticket #JIRA-123.
 - Why?: These changes complete the user login and account creation experience. See #JIRA-123 for more information.

 # Testing
 Help me how can I test or look at the changes

 Example:
  - I've added coverage for testing all new methods. I used Faker for a few random user emails and names.

  ## Screenshots
If applicable, include screenshots of the results or screenshots that help to see changes

### CODE REVIEW

File: app/controllers/crud_controller.rb [hunk 1]
```diff
@@ -1,4 +1,58 @@
-class CrudController < ApplicationController
-  def index
+  class CrudController < ApplicationController
```
Comment (xFerchoVJ) [inline app/controllers/crud_controller.rb]: You should be more specific with the name of their controllers, for example I see that this controller is for employees, so I would recommend instead of calling it CrudController it be EmployeeController

**Review by xFerchoVJ — DISMISSED** [review]
Everything looks good to me, As a recommendation you could add some validations in your models

[https://codigofacilito.com/articulos/validaciones-ror](https://makeitrealcamp.gitbook.io/ruby-on-rails-5/13-validaciones)

[https://makeitrealcamp.gitbook.io/ruby-on-rails-5/13-validaciones](https://makeitrealcamp.gitbook.io/ruby-on-rails-5/13-validaciones)
