### PR TITLE
Employee-controller-employee-model-employee-frontend-fixes

### LINKED ISSUE #12: Employee controller, employee model, employee frontend fixes
# REQUIREMENTS
Add controller to let the employees check in and check out

# DESIGN

### PR DESCRIPTION
**Pull request by javs1**
routes.rb
 - added post check route to the employee check controller method
employee.html.erb
 - modified submit button of check in and check out to sent as parameter
   the name
 - added a notice and alert paragraph to Feedback to employee on
   successful/failed registration
created Check model
employee_helper.rb
 - method check_value returns 1 or 0 based on the parameter if true or
   false
 - method check_save save the check in the database and returns the
   feedback message
employee_controller.rb
 - added check method
 - check method search the employee by the privateNumber from the
   parameter
 - check method save the check and feedback the employee

Co-authored-by: Joshsam31 <samano82324@gmail.com>
Co-authored-by: javs1 <javierverduzco13@gmail.com>

### CODE REVIEW

File: app/helpers/employee_helper.rb [hunk 1]
```diff
@@ -0,0 +1,20 @@
+module EmployeeHelper
+
+  def check_value(check)
+    if check
+      1
+    else
+      0
+    end
```
Comment (JuanequeX) [inline app/helpers/employee_helper.rb]: In this condition can be use a ternary operator same like in at that your check_save conditional.

File: app/models/check.rb [hunk 2]
```diff
@@ -0,0 +1,3 @@
+class Check < ApplicationRecord
+    
+end
```
Comment (JuanequeX) [inline app/models/check.rb]: Add a blank line here

**Review by JuanequeX — CHANGES_REQUESTED** [review]

File: app/views/employee/employee.html.erb [hunk 3]
```diff
@@ -3,23 +3,28 @@
 	</head>
 	<body>
```
Comment (YilKanda) [inline app/views/employee/employee.html.erb]: Why do you have html, head and body tags in this file? Remember that these tags appear in application.erb

**Review by YilKanda — COMMENTED** [review]
Remember to leave an indentation of 2 spaces in all your files.

File: app/helpers/employee_helper.rb (hunk 1 above)
Comment (xFerchoVJ) [reply app/helpers/employee_helper.rb]: I agree with that.

File: config/routes.rb [hunk 4]
```diff
@@ -1,7 +1,12 @@
 Rails.application.routes.draw do
-  get 'crud', to: "crud#index"
+  get 'crud', to: "employee_crud#index"
+  get 'crud/:id', to: "employee_crud#index"
   get 'admin', to: "home#index"
   post 'admin', to: "home#login"
+  post 'logout', to: "employee_crud#logout"
+  post 'createEmployee', to: "employee_crud#create"
```
Comment (EduardoGHdez) [inline config/routes.rb]: In ruby, it's preferred to use snake-case rather than camelcase. It's just a convention and there is no harm on doing so, but I'd recommend following the conventions, so you get used to them 😄
